### ISSUE TITLE
NameError when TargetRubyVersion is not set

### ISSUE THREAD

**Issue by r00takaspin** [m4i/rubocop-git#24]
NameError when TargetRubyVersion is not set in .rubocop.yml

``````
➜   bundle exec rubocop-git
/Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/style_guide.rb:75:in `target_ruby_version': uninitialized constant RuboCop::Git::StyleGuide::ValidationError (NameError)
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/style_guide.rb:36:in `parse_source'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/style_guide.rb:14:in `violations'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/style_checker.rb:27:in `offenses'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/style_checker.rb:16:in `block in violations'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/style_checker.rb:15:in `map'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/style_checker.rb:15:in `violations'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/runner.rb:21:in `violations'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/runner.rb:49:in `display_violations'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/runner.rb:13:in `run'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/lib/rubocop/git/cli.rb:10:in `run'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/gems/rubocop-git-0.1.1/bin/rubocop-git:5:in `<top (required)>'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/bin/rubocop-git:23:in `load'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/bin/rubocop-git:23:in `<main>'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
        from /Users/voldemar/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'```
``````

**Comment by m4i** [comment]
Thank you for your reporting. 
This bug was probably fixed in #26 and 0.1.2.
If the problem still occurs, please reopen.
